"""empty message

Revision ID: 08607ce0b7f0
Revises: 882cb7770496
Create Date: 2023-12-23 12:26:39.744561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08607ce0b7f0'
down_revision = '882cb7770496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses_to_competitions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_horses_to_competitions_competition_id_competitions', type_='foreignkey')
        batch_op.drop_constraint('fk_horses_to_competitions_horse_id_horses', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_horses_to_competitions_competition_id_competitions'), 'competitions', ['competition_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_horses_to_competitions_horse_id_horses'), 'horses', ['horse_id'], ['id'])

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_results_competition_id_competitions', type_='foreignkey')
        batch_op.drop_constraint('fk_results_horse_id_horses', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_results_competition_id_competitions'), 'competitions', ['competition_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_results_horse_id_horses'), 'horses', ['horse_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_results_horse_id_horses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_results_competition_id_competitions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_results_horse_id_horses', 'horses', ['horse_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_results_competition_id_competitions', 'competitions', ['competition_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('horses_to_competitions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_horses_to_competitions_horse_id_horses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_horses_to_competitions_competition_id_competitions'), type_='foreignkey')
        batch_op.create_foreign_key('fk_horses_to_competitions_horse_id_horses', 'horses', ['horse_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_horses_to_competitions_competition_id_competitions', 'competitions', ['competition_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
