"""Initial migration

Revision ID: 53c53bb775d3
Revises: 
Create Date: 2023-10-30 13:50:20.513781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c53bb775d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions'))
    )
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genders'))
    )
    op.create_table('jokeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jokeys'))
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('jokey_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], name=op.f('fk_horses_gender_id_genders')),
    sa.ForeignKeyConstraint(['jokey_id'], ['jokeys.id'], name=op.f('fk_horses_jokey_id_jokeys')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_horses_owner_id_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horses'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('horses_to_competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_horses_to_competitions_competition_id_competitions')),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('fk_horses_to_competitions_horse_id_horses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horses_to_competitions'))
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_results_competition_id_competitions')),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('fk_results_horse_id_horses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('horses_to_competitions')
    op.drop_table('users')
    op.drop_table('horses')
    op.drop_table('roles')
    op.drop_table('owners')
    op.drop_table('jokeys')
    op.drop_table('genders')
    op.drop_table('competitions')
    # ### end Alembic commands ###
