"""empty message

Revision ID: 882cb7770496
Revises: 53c53bb775d3
Create Date: 2023-12-22 16:32:20.105757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '882cb7770496'
down_revision = '53c53bb775d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('test')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=100),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
