FROM python:3.12
EXPOSE 8000
WORKDIR /usr/app

COPY requirements.txt /usr/app/
RUN pip install Cmake
RUN pip install --only-binary :all: greenlet
RUN pip install -r requirements.txt
RUN pip install waitress
COPY /app /usr/app/
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8000"]
